---
name: Release
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo tag=${branch#release/} >> $GITHUB_OUTPUT
        id: get-tag-step
  get-rel-notes:
    name: Get release notes
    needs: get-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: networkservicemesh/.github
          path: github
      - name: Install node modules
        run: yarn add @actions/github
      - name: Generate Release Notes
        id: generate-release-notes
        run: |
            ls -ltr github/scripts
            node github/scripts/generate-release-notes.js '${{ secrets.token }}' '${{ needs.get-tag.outputs.tag }}' '${{ github.event.repository.name }}' > notes.txt
      - name: Upload notes for release
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: notes.txt

  create-release:
    name: Create release
    needs: [get-tag, get-rel-notes]
    runs-on: ubuntu-latest
    steps:
      - name: Choose branch
        id: branch
        run: |
          branch=${{ github.event.workflow_run.head_branch }}
          if [ -z "$branch" ]; then
            ref=${{ github.event.ref }}
            branch=${ref#refs/heads/}
          fi
          echo "$branch"
          echo branch=${branch} >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ steps.branch.outputs.branch }}
      - name: Push tag ${{ needs.get-tag.outputs.tag }}
        run: |
          git status
          git tag ${{ needs.get-tag.outputs.tag }}
          git push origin ${{ needs.get-tag.outputs.tag }} -f
      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
      - name: Create release ${{ needs.get-tag.outputs.tag }}
        run: |
          gh release create ${{ needs.get-tag.outputs.tag }} --title ${{ needs.get-tag.outputs.tag }} --target ${{github.event.workflow_run.head_branch}} --notes-file notes.txt
        env:
          GH_TOKEN: ${{ secrets.token }}
